"""Shared runtime constants for kernel initialization and phase controls.

These constants intentionally mirror current runtime behavior. They centralize
high-impact defaults so future phase work can move from hardcoded literals to
explicit configuration without changing semantics.
"""

MIN_OVERRIDE_PHASE_LEVEL = 0
MAX_OVERRIDE_PHASE_LEVEL = 4
CONSOLIDATED_OVERRIDE_DISABLED = -1

HARD_OVERRIDE_PHASE2_THRESHOLD = 2
HARD_OVERRIDE_DISABLE_FRONTIER_LOCK_LEVEL = 1
HARD_OVERRIDE_DISABLE_PERSISTENT_FRONTIER_LEVEL = 2
HARD_OVERRIDE_DISABLE_VERIFICATION_PRIORITY_LEVEL = 3
HARD_OVERRIDE_DISABLE_PLAN_HOLD_LEVEL = 4

LEGACY_ENDOCRINE_STRESS_DANGER_WEIGHT = 18.0
LEGACY_ENDOCRINE_CURIOSITY_NOVELTY_WEIGHT = 14.0
LEGACY_ENDOCRINE_FATIGUE_REPEAT_WEIGHT = 10.0
LEGACY_ENDOCRINE_CONFIDENCE_RISK_BONUS = 8.0
LEGACY_ENDOCRINE_MOMENTUM_BONUS_WEIGHT = 6.0

DEFAULT_HORMONE_LEGACY_WEIGHT_BLEND = 0.35
DEFAULT_HORMONE_LEGACY_BATCH_LEVEL = 1

DEFAULT_OBJECTIVE_OVERRIDE_ENABLE = "1"
DEFAULT_HARD_OVERRIDE_PHASE_LEVEL = "0"
DEFAULT_CONSOLIDATED_OVERRIDE_PHASE_LEVEL = "-1"

DEFAULT_PHASE2_FRONTIER_LOCK_INFLUENCE = "22"
DEFAULT_PHASE2_PERSISTENT_FRONTIER_INFLUENCE = "16"
DEFAULT_PHASE2_VERIFICATION_INFLUENCE = "14"
DEFAULT_PHASE2_PLAN_HOLD_INFLUENCE = "12"

DEFAULT_PHASE_PROGRESS_HEADER_TEXT = "Phase --/-- | KMicro --/--"

DEFAULT_TRAINING_PHASE_ENABLE = "1"
DEFAULT_TRAINING_PHASE_LEVEL = "1"
DEFAULT_TRAINING_PHASE_AUTO_ADVANCE = "1"
DEFAULT_TRAINING_PHASE2_MIN_STEPS = "2500"
DEFAULT_TRAINING_PHASE3_MIN_STEPS = "9000"
DEFAULT_TRAINING_PHASE1_PROJECTION_SCALE = "0.4"
DEFAULT_TRAINING_PHASE2_PROJECTION_SCALE = "0.7"
DEFAULT_TRAINING_PHASE3_PROJECTION_SCALE = "1.0"
DEFAULT_TRAINING_PHASE_OVERRIDE_MIN_PRED_GAP = "0.015"

DEFAULT_KERNEL_MICRO_PHASE_PROGRESSION_ENABLE = "1"
DEFAULT_KERNEL_MICRO_PHASE_PERSIST_ENABLE = "1"
DEFAULT_KERNEL_MICRO_PHASE_TOTAL_STEPS = "24"
DEFAULT_KERNEL_MICRO_PHASE_WARMUP_STEPS = "600"
DEFAULT_KERNEL_MICRO_PHASE_EMA_DECAY = "0.985"
DEFAULT_KERNEL_MICRO_PHASE_PHASE2_RATIO = "0.34"
DEFAULT_KERNEL_MICRO_PHASE_PHASE3_RATIO = "0.67"
DEFAULT_KERNEL_MICRO_PHASE_HARD_BONUS_MAX = "3"
DEFAULT_KERNEL_MICRO_PHASE_OBJECTIVE_BONUS_MAX = "3"
DEFAULT_KERNEL_MICRO_PHASE_PHASE2_SCALE_MIN = "0.45"
DEFAULT_KERNEL_MICRO_PHASE_ALLOW_REGRESSION = "1"
DEFAULT_KERNEL_MICRO_PHASE_REGRESSION_MARGIN = "0.08"
DEFAULT_KERNEL_MICRO_PHASE_SAVE_INTERVAL_STEPS = "24"
DEFAULT_KERNEL_MICRO_PHASE_RETIRE_HARDCODED_ENABLE = "1"
DEFAULT_KERNEL_MICRO_PHASE_RETIRE_MIN_EMA = "0.94"
DEFAULT_KERNEL_MICRO_PHASE_RETIRE_MIN_INDEX_RATIO = "0.98"
DEFAULT_KERNEL_MICRO_PHASE_RETIRE_MAX_INTERVENTION_EMA = "0.22"
DEFAULT_KERNEL_MICRO_PHASE_RETIRE_REQUIRE_PHASE3 = "1"
DEFAULT_KERNEL_MICRO_PHASE_RETIRE_ALLOW_UNRETIRE = "0"
